Trying out a custom action.

diff --git a/.github/actions/publish/action.yml b/.github/actions/publish/action.yml
--- a/.github/actions/publish/action.yml
+++ b/.github/actions/publish/action.yml
@@ -26,11 +26,7 @@ runs:
         echo "Checking tag name: Did regex match? => [${{ steps.regex-match.outputs.match }}]";
         REMATCH="${{ steps.regex-match.outputs.match }}";
         REFNAME="${{ github.ref_name }}";
-        [ -z "$REMATCH" ] && { 
-            echo "ERROR: Tag '$REFNAME' has invalid format." ; 
-            false ;
-        }
-        true
+        [ -z "$REMATCH" ] && error "ERROR: Tag '$REFNAME' has invalid format." 
       shell: bash
 
     - name: Login to docker hub
@@ -38,11 +34,7 @@ runs:
       run: |
         echo "${{ inputs.docker_token }}" \
           | docker login -u "${{ inputs.docker_user }}" --password-stdin \
-          || { 
-            echo "ERROR: Login to docker registry failed." ; 
-            false ; 
-          }
-        true
+          || error "ERROR: Login to docker registry failed."
       shell: bash
 
     - name: Create 
