Trying out a custom action.

diff --git a/.github/actions/publish/action.yml b/.github/actions/publish/action.yml
--- a/.github/actions/publish/action.yml
+++ b/.github/actions/publish/action.yml
@@ -25,25 +25,29 @@ runs:
       run: |
         echo "Checking tag name: Did regex match?";
         [ -z "${{ steps.regex-match.outputs.match }}" ] \
-        && echo "result='Tag ${{ github.ref_name }} has invalid format.'" \
+        && echo "ERROR: Tag '${{ github.ref_name }}'' has invalid format." \
         && false
       shell: bash
 
     - name: Login to docker hub
       id: login-to-docker-hub
       run: |
-        echo "${{ inputs.docker_token }}" | docker login -u "${{ inputs.docker_user }}" --password-stdin
+        echo "${{ inputs.docker_token }}" \
+          | docker login -u "${{ inputs.docker_user }}" --password-stdin \
+          || echo "ERROR: Login to docker registry failed."
       shell: bash
 
     - name: Create 
       id: create
       run: |
-        ./build.sh ${{ inputs.arch }} ${{ github.ref_name }}
+        ./build.sh ${{ inputs.arch }} ${{ github.ref_name }} \
+        || echo "ERROR: Building docker image failed."
       shell: bash
 
     - name: Tag and push 
       id: tag-and-push
       run: |
         IMAGE=$(cat /tmp/IMAGE);
-        docker push $IMAGE
+        docker push $IMAGE \
+        || echo "ERROR: Pushing $IMAGE to docker registry failed."
       shell: bash
