Trying out a custom action.

diff --git a/.github/actions/publish/error b/.github/actions/publish/error
--- a/.github/actions/publish/error
+++ b/.github/actions/publish/error
@@ -1,3 +1,5 @@
-#!/usr/bin/env bash
-echo "ERROR: $@" 
-exit 1
+
+error {
+    echo "ERROR: $@" 
+    exit 1
+}
